{% set name = "arm-test-data" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 72533d6e44792eaca3242bf089b9cef49d1162e369d94df56f79306dba1eca63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - wheel
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - pooch

test:
  imports:
    - arm_test_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ARM-DOE/arm-test-data
  summary: Provides utility functions for accessing data repository for openradar examples/notebooks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgrover1
    - zssherman
