{% set name = "arm-test-data" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arm-test-data-{{ version }}.tar.gz
  sha256: 515e718aacec8699cde34e30e0df8509223c61d654eee2c72e12b75c0fc39f60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - wheel
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - pooch

test:
  imports:
    - arm_test_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ARM-DOE/arm-test-data
  summary: Provides utility functions for accessing data repository for openradar examples/notebooks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgrover1
    - zssherman
